export const DEFAULT_NFE = {
  larguraDaPagina: 595.44,
  alturaDaPagina: 841.68,
  tamanhoDaFonteDoTitulo: 6,
  corDoTitulo: 'black',
  alinhamentoDoTitulo: 'left',
  alinhamentoDoTituloDaTabela: 'center',
  tamanhoDaFonteDaSecao: 7,
  corDaSecao: 'black',
  tamanhoDaFonteDoCampo: 9.5,
  alinhamentoDoCampo: 'center',
  corDoCampo: 'black',
  tamanhoDaFonteDosItens: 7,
  separadorDeItens: true,
  ajusteYDoLogotipo: 0,
  ajusteYDaIdentificacaoDoEmitente: 0,
  opacidadeDaHomologacao: 0.4,
  ajusteYDaHomologacao: 275,
  tamanhoDoCodigoDeBarras: 32,
  corDoLayout: 'black',
  finalTamanhoDet1: 752,
  finalTamanhoDetDemais: 822
} as const;
