export declare const DEFAULT_NFE: {
    readonly larguraDaPagina: 595.44;
    readonly alturaDaPagina: 841.68;
    readonly tamanhoDaFonteDoTitulo: 6;
    readonly corDoTitulo: "black";
    readonly alinhamentoDoTitulo: "left";
    readonly alinhamentoDoTituloDaTabela: "center";
    readonly tamanhoDaFonteDaSecao: 7;
    readonly corDaSecao: "black";
    readonly tamanhoDaFonteDoCampo: 9.5;
    readonly alinhamentoDoCampo: "center";
    readonly corDoCampo: "black";
    readonly tamanhoDaFonteDosItens: 7;
    readonly separadorDeItens: true;
    readonly ajusteYDoLogotipo: 0;
    readonly ajusteYDaIdentificacaoDoEmitente: 0;
    readonly opacidadeDaHomologacao: 0.4;
    readonly ajusteYDaHomologacao: 275;
    readonly tamanhoDoCodigoDeBarras: 32;
    readonly corDoLayout: "black";
    readonly finalTamanhoDet1: 752;
    readonly finalTamanhoDetDemais: 822;
};
