export declare const DEFAULT_NFE: {
    larguraDaPagina: number;
    alturaDaPagina: number;
    tamanhoDaFonteDoTitulo: number;
    corDoTitulo: string;
    alinhamentoDoTitulo: string;
    alinhamentoDoTituloDaTabela: string;
    tamanhoDaFonteDaSecao: number;
    corDaSecao: string;
    tamanhoDaFonteDoCampo: number;
    alinhamentoDoCampo: string;
    corDoCampo: string;
    tamanhoDaFonteDosItens: number;
    separadorDeItens: boolean;
    ajusteYDoLogotipo: number;
    ajusteYDaIdentificacaoDoEmitente: number;
    opacidadeDaHomologacao: number;
    ajusteYDaHomologacao: number;
    tamanhoDoCodigoDeBarras: number;
    corDoLayout: string;
    creditos: string;
};
